# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

source: source

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Prophecy MUD
email: anheg@prophecy.lu
description: >- # this means to ignore newlines until "baseurl:"
 Prophecy: The MUD is a huge world (+121 original areas) run on heavily modified ROM 2.4 code. Prophecy’s content and gaming style is based on the David Eddings fantasy book series The Belgariad and The Malloreon. The books serve as the basis for a character’s race, class, and initial alignment. The game is a natural for roleplay, yet also provides opportunities for restricted player killing. A friendly player base and clans dedicated to new player support make Prophecy the perfect beginner’s gateway to MUDs.


Prophecy features “Immortal”-hosted quests for added amusement and prizes, as well as auto-questing to earn customizable gear, experience, and in-game currency. In addition, unique mini-quests can be found in many areas that offer a challenge as well as rich rewards.


Prophecy MUD was officially ported to the Go language in Decembe r 2019 after years of development, facilitating continuous improvement and ensuring stable gameplay for years to come. “King Anheg” is keeping busy with new changes such as elective ‘hometowns’, ooc buffer retrieval for catching up on the latest public discussions, and other Good Things(TM) !


Are you a Prophecy “veteran”? Drop in and check the place out–we love seeing returning players! If you ever built an area here, it’s most likely still in use (and we thank you!). We’re a no-pwipe MUD, so your character(s), hostel room stash, and quest eq are right where you left them. In any case, if you like the idea of reliving the glory days of ROM MUDs, are a new player looking for a first game to begin your adventures, or simply looking for a place to while away a few hours in one of the longest-running servers out there, point your client to mud.prophecy.lu 4000. Or, for instant gratification, use one of these ready-to-play browser clients!


&bull; [Prophecy MUD on Grapevine](https://grapevine.haus/games/Prophecy/play) 


&bull; [Prophecy MUD on MudPortal](http://www.mudportal.com/play?host=mud.prophecy.lu&port=4000)

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  prophecymud

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
